# Generated by Django 5.2.1 on 2025-07-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_it', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_it', models.TextField()),
                ('extra_info_en', models.CharField(blank=True, max_length=200)),
                ('extra_info_it', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='flyers/')),
                ('event_date', models.DateField()),
            ],
        ),
    ]
