# Generated by Django 5.2.1 on 2025-05-26 13:50

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_it', models.CharField(blank=True, max_length=200, verbose_name='Title (IT)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('body_en', models.TextField(verbose_name='Content (EN)')),
                ('body_it', models.TextField(blank=True, verbose_name='Content (IT)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=blog.models.blog_image_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=blog.models.blog_video_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
