# Generated by Django 5.2.1 on 2025-06-14 16:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_featured_image_alter_blogpost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body_en',
            field=ckeditor.fields.RichTextField(verbose_name='Content (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body_it',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content (IT)'),
        ),
    ]
