# Generated by Django 5.2.1 on 2025-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flyer',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='flyer',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='flyer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='flyer',
            name='description_it',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flyer',
            name='extra_info_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='flyer',
            name='extra_info_it',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='flyer',
            name='title_it',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
