# Generated by Django 5.2.1 on 2025-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='name_en',
            field=models.CharField(default='Unnamed Class', max_length=100, verbose_name='Class Name (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='name_it',
            field=models.CharField(blank=True, max_length=100, verbose_name='Class Name (IT)'),
        ),
    ]
