# Generated by Django 5.2.1 on 2025-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_class_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days_of_week',
            field=models.CharField(blank=True, help_text="For custom repeat, enter days like 'Mon,Wed,Fri'", max_length=20, verbose_name='Days of the Week'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'One-time only'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('custom_days', 'Custom weekdays')], default='none', max_length=20, verbose_name='Repeats'),
        ),
    ]
