# Generated by Django 5.2.1 on 2025-06-14 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_event_days_of_week_event_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_exceptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, help_text='Dates on which this recurring event should be skipped', size=None, verbose_name='Recurrence Exceptions'),
        ),
    ]
