# Generated by Django 5.2.1 on 2025-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_event_recurrence_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeat_until',
            field=models.DateField(blank=True, help_text='Last day this event should occur', null=True, verbose_name='Repeat Until'),
        ),
    ]
