# Generated by Django 5.2.1 on 2025-07-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_flyer_description_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flyer',
        ),
    ]
