# Generated by Django 5.2.1 on 2025-08-23 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0002_alter_flyer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flyer',
            options={'ordering': ['sort_order', 'event_date', 'id']},
        ),
        migrations.AddField(
            model_name='flyer',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False
            ),
        ),
        migrations.AddField(
            model_name='flyer',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='description_it',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='extra_info_en',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='extra_info_it',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='image',
            field=models.ImageField(
                blank=True,
                default='',
                upload_to='flyers/'
            ),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='title_it',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
