# Generated by Django 5.2.1 on 2025-07-12 11:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
